-- Wildlife Sentinel PostgreSQL schema. Run only in an empty application schema.
BEGIN;
-- Refuse an existing application schema. All changes roll back on any error.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema()) THEN
        RAISE EXCEPTION 'Schema is not empty. No existing tables will be overwritten.';
    END IF;
END $$;
CREATE FUNCTION ws_point_from_wkt(value text) RETURNS point LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT replace(regexp_replace(value, '^POINT\((.*)\)$', '\1', 'i'), ' ', ',')::point $$;
CREATE FUNCTION ws_point_to_wkt(value point) RETURNS text LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT 'POINT(' || value[0] || ' ' || value[1] || ')' $$;
CREATE FUNCTION ws_touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at := CURRENT_TIMESTAMP; RETURN NEW; END $$;
CREATE TABLE zones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    center_lat DECIMAL(10, 8) NULL,
    center_lng DECIMAL(11, 8) NULL,
    boundary_geojson JSONB NULL,
    created_by INTEGER NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active SMALLINT DEFAULT 1,
    park_type TEXT CHECK (park_type IN ('national_park','gma','other')) DEFAULT 'other',
    park_code VARCHAR(50) UNIQUE NULL,
    is_registered SMALLINT DEFAULT 0,
    buffer_radius INTEGER DEFAULT 500,
    boundary_center_lat DECIMAL(10, 8) NULL,
    boundary_center_lng DECIMAL(11, 8) NULL,
    area_km2 DECIMAL(12, 2) NULL
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role TEXT CHECK (role IN ('scout','tourism','ranger','zone_supervisor','admin')) NOT NULL,
    zone_id INTEGER NULL,
    is_active SMALLINT DEFAULT 1,
    is_online SMALLINT DEFAULT 0,
    last_seen TIMESTAMP NULL,
    last_online TIMESTAMP NULL,
    is_on_duty SMALLINT DEFAULT 0,
    badge_number VARCHAR(50) NULL,
    fcm_token VARCHAR(255) NULL,
    profile_image VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER NULL,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE SET NULL
);

CREATE TABLE ranger_availability (
    ranger_id INTEGER PRIMARY KEY,
    is_available SMALLINT DEFAULT 1,
    current_incident_id INTEGER NULL,
    last_status_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    shift_start TIME NULL,
    shift_end TIME NULL,
    days_available JSONB NULL,
    FOREIGN KEY (ranger_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE ranger_live_tracking (
    ranger_id INTEGER PRIMARY KEY,
    current_lat DECIMAL(10, 8) NULL,
    current_lng DECIMAL(11, 8) NULL,
    heading DECIMAL(5, 2) NULL,
    speed DECIMAL(6, 2) NULL,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_offline SMALLINT DEFAULT 0,
    FOREIGN KEY (ranger_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE ranger_location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ranger_id INTEGER NOT NULL,
    lat DECIMAL(10, 8) NOT NULL,
    lng DECIMAL(11, 8) NOT NULL,
    heading DECIMAL(5, 2) DEFAULT 0,
    speed DECIMAL(6, 2) DEFAULT 0,
    incident_id INTEGER NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ranger_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE scout_live_tracking (
    scout_id INTEGER PRIMARY KEY,
    current_lat DECIMAL(10, 8) NULL,
    current_lng DECIMAL(11, 8) NULL,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_offline SMALLINT DEFAULT 0,
    FOREIGN KEY (scout_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE scout_location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scout_id INTEGER NOT NULL,
    lat DECIMAL(10, 8) NOT NULL,
    lng DECIMAL(11, 8) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (scout_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE ranger_patrol_routes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ranger_id INTEGER NOT NULL,
    zone_id INTEGER NOT NULL,
    route_name VARCHAR(255) NOT NULL,
    start_lat DECIMAL(10, 8) NOT NULL,
    start_lng DECIMAL(11, 8) NOT NULL,
    end_lat DECIMAL(10, 8) NULL,
    end_lng DECIMAL(11, 8) NULL,
    route_geojson JSONB NULL,
    notes TEXT NULL,
    is_active SMALLINT DEFAULT 1,
    created_by INTEGER NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ranger_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE incidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id INTEGER NOT NULL,
    reporter_type TEXT CHECK (reporter_type IN ('scout','tourism')) NOT NULL,
    zone_id INTEGER NULL,
    category TEXT CHECK (category IN ('poaching','distressed_animal','human_wildlife_conflict','environmental_risk','other')) NOT NULL,
    severity TEXT CHECK (severity IN ('low','medium','high','critical')) DEFAULT 'medium',
    description TEXT NULL,
    location_lat DECIMAL(10, 8) NOT NULL,
    location_lng DECIMAL(11, 8) NOT NULL,
    location_geojson POINT NOT NULL,
    media_urls JSONB NULL,
    status TEXT CHECK (status IN ('reported','acknowledged','in_progress','resolved','closed')) DEFAULT 'reported',
    reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    acknowledged_by INTEGER NULL,
    acknowledged_at TIMESTAMP NULL,
    resolved_at TIMESTAMP NULL,
    is_simulated SMALLINT DEFAULT 0,
    FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE SET NULL,
    FOREIGN KEY (acknowledged_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE incident_responses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER NOT NULL,
    ranger_id INTEGER NOT NULL,
    status_update TEXT CHECK (status_update IN ('arrived','investigating','resolved','escalated')) NOT NULL,
    notes TEXT NULL,
    location_lat DECIMAL(10, 8) NULL,
    location_lng DECIMAL(11, 8) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE CASCADE,
    FOREIGN KEY (ranger_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE incident_assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER NOT NULL,
    ranger_id INTEGER NOT NULL,
    assigned_by INTEGER NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status TEXT CHECK (status IN ('pending','accepted','declined','completed')) DEFAULT 'pending',
    notes TEXT NULL,
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE CASCADE,
    FOREIGN KEY (ranger_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INTEGER NOT NULL,
    recipient_id INTEGER NULL,
    incident_id INTEGER NULL,
    zone_id INTEGER NULL,
    message_type TEXT CHECK (message_type IN ('manpower_request','status_update','general','emergency')) DEFAULT 'general',
    subject VARCHAR(255) NULL,
    content TEXT NOT NULL,
    severity TEXT CHECK (severity IN ('low','medium','high','critical')) DEFAULT 'medium',
    is_broadcast SMALLINT DEFAULT 0,
    is_read SMALLINT DEFAULT 0,
    read_at TIMESTAMP NULL,
    requires_acknowledgment SMALLINT DEFAULT 0,
    acknowledged_at TIMESTAMP NULL,
    parent_message_id INTEGER NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE SET NULL,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE SET NULL,
    FOREIGN KEY (parent_message_id) REFERENCES messages(id) ON DELETE CASCADE
);

CREATE TABLE message_attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_type VARCHAR(50) NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    incident_id INTEGER NULL,
    message_id INTEGER NULL,
    type TEXT CHECK (type IN ('new_incident','acknowledged','status_update','system_alert','new_message','manpower_request')) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NULL,
    is_read SMALLINT DEFAULT 0,
    is_delivered SMALLINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE SET NULL,
    FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE SET NULL
);

CREATE TABLE audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NULL,
    action VARCHAR(100) NOT NULL,
    details JSONB NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE rate_limits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL,
    key_name VARCHAR(100) NOT NULL,
    attempt_count INTEGER DEFAULT 1,
    first_attempt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_anomalies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INTEGER NOT NULL,
    type TEXT CHECK (type IN ('ranger_out_of_bounds','ranger_stationary','patrol_deviation','scout_out_of_bounds','unusual_movement','unusual_cluster','other')) NOT NULL,
    severity TEXT CHECK (severity IN ('low','medium','high','critical')) DEFAULT 'medium',
    description TEXT NULL,
    confidence DECIMAL(4, 3) DEFAULT 0.700,
    location_lat DECIMAL(10, 8) NOT NULL,
    location_lng DECIMAL(11, 8) NOT NULL,
    radius_meters INTEGER DEFAULT 200,
    ranger_id INTEGER NULL,
    scout_id INTEGER NULL,
    is_acknowledged SMALLINT DEFAULT 0,
    acknowledged_by INTEGER NULL,
    acknowledged_at TIMESTAMP NULL,
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (ranger_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (scout_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (acknowledged_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE zone_notification_settings (
    zone_id INTEGER PRIMARY KEY,
    sms_enabled SMALLINT DEFAULT 1,
    alarm_enabled SMALLINT DEFAULT 1,
    ai_detection_enabled SMALLINT DEFAULT 1,
    alarm_delay_seconds INTEGER DEFAULT 120,
    ai_confidence_threshold INTEGER DEFAULT 70,
    auto_create_incidents SMALLINT DEFAULT 1,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE
);

CREATE TABLE zone_system_settings (
    zone_id INTEGER PRIMARY KEY,
    ai_enabled SMALLINT DEFAULT 1,
    ai_confidence_min INTEGER DEFAULT 70,
    ai_auto_create_alert SMALLINT DEFAULT 1,
    ai_auto_trigger_alarm SMALLINT DEFAULT 0,
    ai_detection_types VARCHAR(255) DEFAULT 'human,animal,vehicle,fire,gunshot',
    cctv_retention_days INTEGER DEFAULT 30,
    cctv_default_quality VARCHAR(20) DEFAULT '1080p',
    cctv_auto_record SMALLINT DEFAULT 1,
    cctv_snapshot_dir VARCHAR(255) DEFAULT 'uploads/cctv/',
    alarm_default_type VARCHAR(20) DEFAULT 'siren',
    alarm_siren_duration INTEGER DEFAULT 180,
    alarm_auto_stop SMALLINT DEFAULT 1,
    alarm_sms_blast SMALLINT DEFAULT 1,
    notif_sms SMALLINT DEFAULT 1,
    notif_email SMALLINT DEFAULT 0,
    notif_push SMALLINT DEFAULT 1,
    notif_on_incident SMALLINT DEFAULT 1,
    notif_on_ai_alert SMALLINT DEFAULT 1,
    notif_on_alarm SMALLINT DEFAULT 1,
    notif_on_manpower SMALLINT DEFAULT 1,
    notif_offline_reminder SMALLINT DEFAULT 1,
    perm_rangers_ack SMALLINT DEFAULT 1,
    perm_rangers_trigger_alarm SMALLINT DEFAULT 0,
    perm_rangers_request_manpower SMALLINT DEFAULT 1,
    perm_scouts_report SMALLINT DEFAULT 1,
    perm_scouts_see_sensitive SMALLINT DEFAULT 0,
    perm_tourism_see_risk SMALLINT DEFAULT 1,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE
);

CREATE TABLE user_preferences (
    user_id INTEGER PRIMARY KEY,
    theme VARCHAR(20) DEFAULT 'light',
    language VARCHAR(10) DEFAULT 'en',
    timezone VARCHAR(50) DEFAULT 'Africa/Lusaka',
    date_format VARCHAR(50) DEFAULT 'M j, Y H:i',
    items_per_page INTEGER DEFAULT 25,
    email_notifications SMALLINT DEFAULT 1,
    sms_notifications SMALLINT DEFAULT 1,
    push_notifications SMALLINT DEFAULT 1,
    notify_incident_updates SMALLINT DEFAULT 1,
    notify_ranger_responses SMALLINT DEFAULT 1,
    notify_safety_alerts SMALLINT DEFAULT 1,
    notify_nearby_incidents SMALLINT DEFAULT 1,
    notify_manpower SMALLINT DEFAULT 1,
    notify_alarms SMALLINT DEFAULT 1,
    quiet_hours_start TIME DEFAULT NULL,
    quiet_hours_end TIME DEFAULT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE lodges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    location_lat DECIMAL(10, 8) NULL,
    location_lng DECIMAL(11, 8) NULL,
    is_active SMALLINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE
);

CREATE TABLE settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_value TEXT NULL,
    setting_group VARCHAR(50) DEFAULT 'general',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER NULL
);

CREATE TABLE cctv_cameras (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INTEGER NOT NULL,
    camera_name VARCHAR(255) NOT NULL,
    camera_code VARCHAR(50) NULL,
    stream_url VARCHAR(500) NULL,
    location_lat DECIMAL(10,8) NULL,
    location_lng DECIMAL(11,8) NULL,
    camera_type TEXT CHECK (camera_type IN ('fixed','ptz','thermal','drone')) DEFAULT 'fixed',
    resolution VARCHAR(20) DEFAULT '1080p',
    is_active SMALLINT DEFAULT 1,
    is_recording SMALLINT DEFAULT 0,
    last_seen TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE
);

CREATE TABLE ai_detections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id INTEGER NULL,
    zone_id INTEGER NOT NULL,
    detection_type TEXT CHECK (detection_type IN ('human','animal','vehicle','fire','gunshot','unknown')) NOT NULL,
    confidence DECIMAL(4,3) DEFAULT 0.700,
    is_threat SMALLINT DEFAULT 0,
    threat_level TEXT CHECK (threat_level IN ('low','medium','high','critical')) DEFAULT 'low',
    snapshot_url VARCHAR(500) NULL,
    location_lat DECIMAL(10,8) NULL,
    location_lng DECIMAL(11,8) NULL,
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (camera_id) REFERENCES cctv_cameras(id) ON DELETE SET NULL
);

CREATE TABLE ai_alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detection_id INTEGER NULL,
    zone_id INTEGER NOT NULL,
    alert_type TEXT CHECK (alert_type IN ('poaching_suspect','intruder','fire','gunshot','animal_distress','other')) NOT NULL,
    severity TEXT CHECK (severity IN ('low','medium','high','critical')) DEFAULT 'medium',
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    location_lat DECIMAL(10,8) NULL,
    location_lng DECIMAL(11,8) NULL,
    is_acknowledged SMALLINT DEFAULT 0,
    acknowledged_by INTEGER NULL,
    acknowledged_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (detection_id) REFERENCES ai_detections(id) ON DELETE SET NULL,
    FOREIGN KEY (acknowledged_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE alarm_systems (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INTEGER NOT NULL,
    alarm_name VARCHAR(255) NOT NULL,
    alarm_code VARCHAR(60) NULL,
    alarm_type TEXT CHECK (alarm_type IN ('siren','bell','strobe','speaker','combined')) DEFAULT 'siren',
    sound_url VARCHAR(500) NULL,
    sound_volume INTEGER DEFAULT 80,
    siren_duration INTEGER DEFAULT 180,
    trigger_delay_seconds INTEGER DEFAULT 120,
    auto_sound_on_incident SMALLINT DEFAULT 1,
    api_endpoint VARCHAR(500) NULL,
    api_key VARCHAR(255) NULL,
    trigger_duration INTEGER DEFAULT 60,
    auto_trigger SMALLINT DEFAULT 1,
    max_acknowledge_time_seconds INTEGER DEFAULT 120,
    location_lat DECIMAL(10,8) NULL,
    location_lng DECIMAL(11,8) NULL,
    is_active SMALLINT DEFAULT 1,
    last_triggered TIMESTAMP NULL,
    trigger_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE
);

CREATE TABLE alarm_triggers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_id INTEGER NULL,
    alert_id INTEGER NULL,
    incident_id INTEGER NULL,
    zone_id INTEGER NOT NULL,
    triggered_by TEXT CHECK (triggered_by IN ('ai_detection','manual','schedule','auto_incident','unacknowledged_incident','scheduled_test')) DEFAULT 'manual',
    trigger_reason VARCHAR(255) NULL,
    triggered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    stopped_at TIMESTAMP NULL,
    duration_seconds INTEGER NULL,
    was_acknowledged SMALLINT DEFAULT 0,
    acknowledged_by INTEGER NULL,
    acknowledged_at TIMESTAMP NULL,
    FOREIGN KEY (alarm_id) REFERENCES alarm_systems(id) ON DELETE SET NULL,
    FOREIGN KEY (alert_id) REFERENCES ai_alerts(id) ON DELETE SET NULL,
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE SET NULL,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (acknowledged_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE sms_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NULL,
    phone VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    message_type TEXT CHECK (message_type IN ('general','incident','ai_alert','manpower','system','test','broadcast')) DEFAULT 'general',
    incident_id INTEGER NULL,
    alert_id INTEGER NULL,
    status TEXT CHECK (status IN ('pending','sent','failed','delivered')) DEFAULT 'pending',
    provider VARCHAR(50) NULL,
    provider_ref VARCHAR(120) NULL,
    gateway_response TEXT NULL,
    segments SMALLINT DEFAULT 1,
    sent_at TIMESTAMP NULL,
    delivered_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE admin_ai_settings (
    admin_id INTEGER PRIMARY KEY,
    sound_alerts_enabled SMALLINT DEFAULT 1,
    auto_ack_low_risk SMALLINT DEFAULT 0,
    auto_ack_minutes INTEGER DEFAULT 10,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE zone_ai_settings (
    zone_id INTEGER PRIMARY KEY,
    sound_alerts_enabled SMALLINT DEFAULT 1,
    auto_ack_low_risk SMALLINT DEFAULT 0,
    auto_ack_minutes INTEGER DEFAULT 10,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE
);

CREATE TABLE simulation_controls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INTEGER NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    simulation_type TEXT CHECK (simulation_type IN ('incident','ai_detection','alarm','sms','ranger_movement')) NOT NULL,
    is_enabled SMALLINT DEFAULT 0,
    parameters JSONB NULL,
    started_at TIMESTAMP NULL,
    stopped_at TIMESTAMP NULL,
    created_by INTEGER NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE simulation_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INTEGER NOT NULL,
    actor_id INTEGER NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    description TEXT NULL,
    payload TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE sms_messages (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id         INTEGER NOT NULL,
    sender_id       INTEGER NOT NULL,
    recipient_id    INTEGER NULL,
    recipient_phone VARCHAR(20) NOT NULL,
    recipient_name  VARCHAR(100) NULL,
    message         TEXT NOT NULL,
    template_key    VARCHAR(50) NULL,
    status TEXT CHECK (status IN ('pending','sent','delivered','failed')) DEFAULT 'pending',
    provider        VARCHAR(50) NULL,
    provider_ref    VARCHAR(120) NULL,
    error_message   TEXT NULL,
    segments        SMALLINT DEFAULT 1,
    sent_at         TIMESTAMP NULL,
    delivered_at    TIMESTAMP NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE ai_models (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    version VARCHAR(30) NOT NULL,
    model_type TEXT CHECK (model_type IN ('detector','classifier','tracker','behavior','fusion')) NOT NULL,
    framework VARCHAR(50) NULL,
    endpoint VARCHAR(500) NULL,
    weights_path VARCHAR(500) NULL,
    input_size VARCHAR(20) DEFAULT '640x640',
    precision_level TEXT CHECK (precision_level IN ('fp32','fp16','int8')) DEFAULT 'fp16',
    avg_latency_ms INTEGER DEFAULT 0,
    accuracy DECIMAL(5,4) NULL,
    is_active SMALLINT DEFAULT 1,
    is_default SMALLINT DEFAULT 0,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, version)
);

CREATE TABLE ai_detections_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_detection_id INTEGER NULL,
    camera_id INTEGER NULL,
    zone_id INTEGER NOT NULL,
    detection_type TEXT CHECK (detection_type IN ('human','animal','vehicle','fire','gunshot','unknown')) NOT NULL,
    subclass VARCHAR(60) NULL,
    confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    ensemble_confidence DECIMAL(5,4) NULL,
    bbox_x DECIMAL(7,4) NULL,
    bbox_y DECIMAL(7,4) NULL,
    bbox_w DECIMAL(7,4) NULL,
    bbox_h DECIMAL(7,4) NULL,
    track_id VARCHAR(60) NULL,
    frame_count INTEGER DEFAULT 1,
    first_seen TIMESTAMP NULL,
    last_seen TIMESTAMP NULL,
    behaviour VARCHAR(60) NULL,
    behaviour_score DECIMAL(5,4) NULL,
    heading_degrees DECIMAL(6,2) NULL,
    speed_mps DECIMAL(6,2) NULL,
    is_threat SMALLINT DEFAULT 0,
    threat_level TEXT CHECK (threat_level IN ('low','medium','high','critical')) DEFAULT 'low',
    threat_score DECIMAL(6,3) DEFAULT 0.000,
    inside_zone SMALLINT DEFAULT 1,
    near_boundary SMALLINT DEFAULT 0,
    distance_to_boundary_m INTEGER NULL,
    is_night SMALLINT DEFAULT 0,
    weather VARCHAR(30) NULL,
    model_id INTEGER NULL,
    ensemble_models JSONB NULL,
    snapshot_url VARCHAR(500) NULL,
    clip_url VARCHAR(500) NULL,
    location_lat DECIMAL(10,8) NULL,
    location_lng DECIMAL(11,8) NULL,
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (camera_id) REFERENCES cctv_cameras(id) ON DELETE SET NULL,
    FOREIGN KEY (model_id) REFERENCES ai_models(id) ON DELETE SET NULL
);

CREATE TABLE ai_tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_uid VARCHAR(60) NOT NULL,
    zone_id INTEGER NOT NULL,
    camera_id INTEGER NULL,
    primary_type TEXT CHECK (primary_type IN ('human','animal','vehicle','fire','gunshot','unknown')) NOT NULL,
    subclass VARCHAR(60) NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NULL,
    duration_seconds INTEGER NULL,
    distance_meters DECIMAL(10,2) NULL,
    avg_speed_mps DECIMAL(6,2) NULL,
    max_speed_mps DECIMAL(6,2) NULL,
    start_lat DECIMAL(10,8) NULL,
    start_lng DECIMAL(11,8) NULL,
    end_lat DECIMAL(10,8) NULL,
    end_lng DECIMAL(11,8) NULL,
    path_geojson JSONB NULL,
    frame_count INTEGER DEFAULT 1,
    peak_confidence DECIMAL(5,4) NULL,
    peak_threat_score DECIMAL(6,3) NULL,
    is_active SMALLINT DEFAULT 1,
    is_confirmed SMALLINT DEFAULT 0,
    last_detected_at TIMESTAMP NULL,
    UNIQUE (track_uid),
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE,
    FOREIGN KEY (camera_id) REFERENCES cctv_cameras(id) ON DELETE SET NULL
);

CREATE TABLE ai_thresholds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INTEGER NULL,
    camera_id INTEGER NULL,
    detection_type TEXT CHECK (detection_type IN ('human','animal','vehicle','fire','gunshot','unknown')) NULL,
    min_confidence DECIMAL(5,4) DEFAULT 0.7000,
    min_ensemble_confidence DECIMAL(5,4) DEFAULT 0.7500,
    min_threat_score DECIMAL(6,3) DEFAULT 40.000,
    min_track_frames INTEGER DEFAULT 2,
    cooldown_seconds INTEGER DEFAULT 45,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    rule_key VARCHAR(80) NOT NULL,
    description TEXT NULL,
    detection_type TEXT CHECK (detection_type IN ('human','animal','vehicle','fire','gunshot','unknown')) NULL,
    condition_json JSONB NOT NULL,
    threat_level TEXT CHECK (threat_level IN ('low','medium','high','critical')) DEFAULT 'medium',
    weight DECIMAL(5,2) DEFAULT 10.00,
    is_active SMALLINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (rule_key)
);

CREATE TABLE ai_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detection_v2_id BIGINT NULL,
    alert_id INTEGER NULL,
    user_id INTEGER NOT NULL,
    verdict TEXT CHECK (verdict IN ('true_positive','false_positive','uncertain')) NOT NULL,
    notes TEXT NULL,
    original_type VARCHAR(60) NULL,
    original_confidence DECIMAL(5,4) NULL,
    corrected_type VARCHAR(60) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (detection_v2_id) REFERENCES ai_detections_v2(id) ON DELETE SET NULL,
    FOREIGN KEY (alert_id) REFERENCES ai_alerts(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE ai_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id INTEGER NULL,
    camera_id INTEGER NULL,
    zone_id INTEGER NULL,
    window_start TIMESTAMP NOT NULL,
    window_seconds INTEGER DEFAULT 60,
    frames_processed INTEGER DEFAULT 0,
    detections_emitted INTEGER DEFAULT 0,
    avg_latency_ms INTEGER DEFAULT 0,
    p95_latency_ms INTEGER DEFAULT 0,
    gpu_util_pct DECIMAL(5,2) NULL,
    cpu_util_pct DECIMAL(5,2) NULL,
    errors INTEGER DEFAULT 0
);

CREATE TABLE ai_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type TEXT CHECK (job_type IN ('detect','track','behaviour','threat','alert','recalibrate')) NOT NULL,
    priority SMALLINT DEFAULT 5,
    zone_id INTEGER NULL,
    camera_id INTEGER NULL,
    payload JSONB NOT NULL,
    status TEXT CHECK (status IN ('pending','processing','done','failed')) DEFAULT 'pending',
    attempts SMALLINT DEFAULT 0,
    max_attempts SMALLINT DEFAULT 3,
    result JSONB NULL,
    error TEXT NULL,
    scheduled_for TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL
);
CREATE INDEX zones_idx_active ON zones (is_active);
CREATE INDEX zones_idx_park_type ON zones (park_type);
CREATE INDEX zones_idx_is_registered ON zones (is_registered);
CREATE INDEX users_idx_role ON users (role);
CREATE INDEX users_idx_zone ON users (zone_id);
CREATE INDEX users_idx_active ON users (is_active);
CREATE INDEX users_idx_online ON users (is_online);
CREATE INDEX ranger_location_history_idx_ranger_time ON ranger_location_history (ranger_id, timestamp);
CREATE INDEX ranger_location_history_idx_timestamp ON ranger_location_history (timestamp);
CREATE INDEX scout_location_history_idx_scout_time ON scout_location_history (scout_id, timestamp);
CREATE INDEX scout_location_history_idx_timestamp ON scout_location_history (timestamp);
CREATE INDEX ranger_patrol_routes_idx_ranger ON ranger_patrol_routes (ranger_id);
CREATE INDEX ranger_patrol_routes_idx_zone ON ranger_patrol_routes (zone_id);
CREATE INDEX incidents_idx_zone ON incidents (zone_id);
CREATE INDEX incidents_idx_status ON incidents (status);
CREATE INDEX incidents_idx_severity ON incidents (severity);
CREATE INDEX incidents_idx_reported_at ON incidents (reported_at);
CREATE INDEX incidents_idx_location ON incidents USING gist (location_geojson);
CREATE INDEX incident_responses_idx_incident ON incident_responses (incident_id);
CREATE INDEX incident_assignments_idx_incident ON incident_assignments (incident_id);
CREATE INDEX incident_assignments_idx_ranger ON incident_assignments (ranger_id);
CREATE INDEX messages_idx_sender ON messages (sender_id);
CREATE INDEX messages_idx_recipient ON messages (recipient_id);
CREATE INDEX messages_idx_incident ON messages (incident_id);
CREATE INDEX messages_idx_zone ON messages (zone_id);
CREATE INDEX messages_idx_type ON messages (message_type);
CREATE INDEX notifications_idx_user ON notifications (user_id);
CREATE INDEX notifications_idx_read ON notifications (is_read);
CREATE INDEX audit_logs_idx_user ON audit_logs (user_id);
CREATE INDEX audit_logs_idx_action ON audit_logs (action);
CREATE INDEX rate_limits_idx_ip_key ON rate_limits (ip_address, key_name);
CREATE INDEX ai_anomalies_idx_zone_time ON ai_anomalies (zone_id, detected_at);
CREATE INDEX ai_anomalies_idx_severity ON ai_anomalies (severity);
CREATE INDEX ai_anomalies_idx_type ON ai_anomalies (type);
CREATE INDEX lodges_idx_zone ON lodges (zone_id);
CREATE INDEX settings_idx_group ON settings (setting_group);
CREATE INDEX settings_idx_key ON settings (setting_key);
CREATE INDEX cctv_cameras_idx_zone ON cctv_cameras (zone_id);
CREATE INDEX cctv_cameras_idx_active ON cctv_cameras (is_active);
CREATE INDEX ai_detections_idx_zone ON ai_detections (zone_id);
CREATE INDEX ai_detections_idx_camera ON ai_detections (camera_id);
CREATE INDEX ai_detections_idx_detected ON ai_detections (detected_at);
CREATE INDEX ai_detections_idx_threat ON ai_detections (is_threat);
CREATE INDEX ai_alerts_idx_zone ON ai_alerts (zone_id);
CREATE INDEX ai_alerts_idx_ack ON ai_alerts (is_acknowledged);
CREATE INDEX alarm_systems_idx_zone ON alarm_systems (zone_id);
CREATE INDEX alarm_systems_idx_active ON alarm_systems (is_active);
CREATE INDEX alarm_triggers_idx_zone ON alarm_triggers (zone_id);
CREATE INDEX alarm_triggers_idx_alarm ON alarm_triggers (alarm_id);
CREATE INDEX alarm_triggers_idx_alert ON alarm_triggers (alert_id);
CREATE INDEX alarm_triggers_idx_incident ON alarm_triggers (incident_id);
CREATE INDEX alarm_triggers_idx_active ON alarm_triggers (stopped_at);
CREATE INDEX sms_logs_idx_user ON sms_logs (user_id);
CREATE INDEX sms_logs_idx_phone ON sms_logs (phone);
CREATE INDEX sms_logs_idx_status ON sms_logs (status);
CREATE INDEX sms_logs_idx_created ON sms_logs (created_at);
CREATE INDEX simulation_controls_idx_zone ON simulation_controls (zone_id);
CREATE INDEX simulation_controls_idx_enabled ON simulation_controls (is_enabled);
CREATE INDEX simulation_events_idx_zone ON simulation_events (zone_id);
CREATE INDEX simulation_events_idx_actor ON simulation_events (actor_id);
CREATE INDEX sms_messages_idx_zone ON sms_messages (zone_id);
CREATE INDEX sms_messages_idx_sender ON sms_messages (sender_id);
CREATE INDEX sms_messages_idx_recipient ON sms_messages (recipient_id);
CREATE INDEX sms_messages_idx_status ON sms_messages (status);
CREATE INDEX sms_messages_idx_created ON sms_messages (created_at);
CREATE INDEX ai_models_idx_active_default ON ai_models (is_active, is_default);
CREATE INDEX ai_detections_v2_idx_zone_time ON ai_detections_v2 (zone_id, detected_at);
CREATE INDEX ai_detections_v2_idx_type_time ON ai_detections_v2 (detection_type, detected_at);
CREATE INDEX ai_detections_v2_idx_track ON ai_detections_v2 (track_id);
CREATE INDEX ai_detections_v2_idx_threat_score ON ai_detections_v2 (threat_score);
CREATE INDEX ai_detections_v2_idx_threat_level ON ai_detections_v2 (threat_level);
CREATE INDEX ai_detections_v2_idx_camera_time ON ai_detections_v2 (camera_id, detected_at);
CREATE INDEX ai_tracks_idx_zone_time ON ai_tracks (zone_id, start_time);
CREATE INDEX ai_tracks_idx_active ON ai_tracks (is_active);
CREATE INDEX ai_tracks_idx_type ON ai_tracks (primary_type);
CREATE INDEX ai_thresholds_idx_zone ON ai_thresholds (zone_id);
CREATE INDEX ai_thresholds_idx_camera ON ai_thresholds (camera_id);
CREATE INDEX ai_thresholds_idx_type ON ai_thresholds (detection_type);
CREATE INDEX ai_rules_idx_active ON ai_rules (is_active);
CREATE INDEX ai_rules_idx_type ON ai_rules (detection_type);
CREATE INDEX ai_feedback_idx_detection ON ai_feedback (detection_v2_id);
CREATE INDEX ai_feedback_idx_alert ON ai_feedback (alert_id);
CREATE INDEX ai_feedback_idx_verdict ON ai_feedback (verdict);
CREATE INDEX ai_telemetry_idx_model_time ON ai_telemetry (model_id, window_start);
CREATE INDEX ai_telemetry_idx_camera_time ON ai_telemetry (camera_id, window_start);
CREATE INDEX ai_telemetry_idx_zone_time ON ai_telemetry (zone_id, window_start);
CREATE INDEX ai_queue_idx_status_priority ON ai_queue (status, priority, scheduled_for);
CREATE INDEX ai_queue_idx_zone ON ai_queue (zone_id);
CREATE INDEX ai_queue_idx_camera ON ai_queue (camera_id);
CREATE TRIGGER zone_notification_settings_touch BEFORE UPDATE ON zone_notification_settings FOR EACH ROW EXECUTE FUNCTION ws_touch_updated_at();
CREATE TRIGGER zone_system_settings_touch BEFORE UPDATE ON zone_system_settings FOR EACH ROW EXECUTE FUNCTION ws_touch_updated_at();
CREATE TRIGGER user_preferences_touch BEFORE UPDATE ON user_preferences FOR EACH ROW EXECUTE FUNCTION ws_touch_updated_at();
CREATE TRIGGER settings_touch BEFORE UPDATE ON settings FOR EACH ROW EXECUTE FUNCTION ws_touch_updated_at();
CREATE TRIGGER admin_ai_settings_touch BEFORE UPDATE ON admin_ai_settings FOR EACH ROW EXECUTE FUNCTION ws_touch_updated_at();
CREATE TRIGGER zone_ai_settings_touch BEFORE UPDATE ON zone_ai_settings FOR EACH ROW EXECUTE FUNCTION ws_touch_updated_at();
CREATE TRIGGER ai_models_touch BEFORE UPDATE ON ai_models FOR EACH ROW EXECUTE FUNCTION ws_touch_updated_at();
CREATE TRIGGER ai_thresholds_touch BEFORE UPDATE ON ai_thresholds FOR EACH ROW EXECUTE FUNCTION ws_touch_updated_at();
INSERT INTO zones (name, description, center_lat, center_lng, is_active)
VALUES ('Headquarters', 'Main Administrative Zone - Lusaka, Zambia', -15.3875, 28.3228, 1);

INSERT INTO zones (name, description, park_type, park_code, is_registered, center_lat, center_lng, boundary_center_lat, boundary_center_lng, boundary_geojson, is_active, buffer_radius) VALUES
('South Luangwa National Park', 'One of Africa''s greatest wildlife sanctuaries, home to elephants, hippos, and the famous Luangwa lions.', 'national_park', 'SLNP', 0, -13.0000, 31.5000, -13.0000, 31.5000, '{"type":"Polygon","coordinates":[[[31.0,-13.5],[32.0,-13.5],[32.0,-12.5],[31.0,-12.5],[31.0,-13.5]]]}', 1, 500),
('Kafue National Park', 'Zambia''s largest national park, covering over 22,000 km² of pristine wilderness.', 'national_park', 'KNP', 0, -14.5000, 26.0000, -14.5000, 26.0000, '{"type":"Polygon","coordinates":[[[25.5,-15.0],[26.5,-15.0],[26.5,-14.0],[25.5,-14.0],[25.5,-15.0]]]}', 1, 500),
('Lower Zambezi National Park', 'Located along the Zambezi River, famous for canoeing safaris and elephant herds.', 'national_park', 'LZNP', 0, -15.5000, 29.5000, -15.5000, 29.5000, '{"type":"Polygon","coordinates":[[[29.0,-16.0],[30.0,-16.0],[30.0,-15.0],[29.0,-15.0],[29.0,-16.0]]]}', 1, 500),
('North Luangwa National Park', 'Remote wilderness known for rhino conservation and untouched landscapes.', 'national_park', 'NLNP', 0, -12.0000, 32.0000, -12.0000, 32.0000, '{"type":"Polygon","coordinates":[[[31.5,-12.5],[32.5,-12.5],[32.5,-11.5],[31.5,-11.5],[31.5,-12.5]]]}', 1, 500),
('Liuwa Plain National Park', 'Home to the famous Liuwa wildebeest migration and spectacular open plains.', 'national_park', 'LPNP', 0, -14.5000, 23.0000, -14.5000, 23.0000, '{"type":"Polygon","coordinates":[[[22.5,-15.0],[23.5,-15.0],[23.5,-14.0],[22.5,-14.0],[22.5,-15.0]]]}', 1, 500),
('Mosi-oa-Tunya National Park', 'Victoria Falls area, home to white rhino and spectacular views of the falls.', 'national_park', 'MOTNP', 0, -17.9000, 25.8000, -17.9000, 25.8000, '{"type":"Polygon","coordinates":[[[25.5,-18.2],[26.1,-18.2],[26.1,-17.7],[25.5,-17.7],[25.5,-18.2]]]}', 1, 500),
('Kasanka National Park', 'Famous for the annual bat migration and diverse bird species.', 'national_park', 'KSNP', 0, -12.5000, 30.0000, -12.5000, 30.0000, '{"type":"Polygon","coordinates":[[[29.5,-13.0],[30.5,-13.0],[30.5,-12.0],[29.5,-12.0],[29.5,-13.0]]]}', 1, 500),
('Sumbu National Park', 'Located on Lake Tanganyika, known for its pristine beaches and marine life.', 'national_park', 'SNP', 0, -8.5000, 30.5000, -8.5000, 30.5000, '{"type":"Polygon","coordinates":[[[30.0,-9.0],[31.0,-9.0],[31.0,-8.0],[30.0,-8.0],[30.0,-9.0]]]}', 1, 500),
('Lochinvar National Park', 'Important wetland area with diverse bird species and Kafue lechwe.', 'national_park', 'LNP', 0, -15.5000, 27.5000, -15.5000, 27.5000, '{"type":"Polygon","coordinates":[[[27.0,-16.0],[28.0,-16.0],[28.0,-15.0],[27.0,-15.0],[27.0,-16.0]]]}', 1, 500),
('Blue Lagoon National Park', 'Wetland paradise on the Kafue Flats, famous for bird watching.', 'national_park', 'BLNP', 0, -15.5000, 27.0000, -15.5000, 27.0000, '{"type":"Polygon","coordinates":[[[26.5,-16.0],[27.5,-16.0],[27.5,-15.0],[26.5,-15.0],[26.5,-16.0]]]}', 1, 500);

INSERT INTO zones (name, description, park_type, park_code, is_registered, center_lat, center_lng, boundary_center_lat, boundary_center_lng, boundary_geojson, is_active, buffer_radius) VALUES
('Luangwa Game Management Area', 'Critical buffer zone surrounding South and North Luangwa National Parks.', 'gma', 'LGMA', 0, -12.5000, 31.5000, -12.5000, 31.5000, '{"type":"Polygon","coordinates":[[[30.5,-13.0],[32.5,-13.0],[32.5,-11.5],[30.5,-11.5],[30.5,-13.0]]]}', 1, 500),
('Kafue Game Management Area', 'Buffer zone around Kafue National Park, important for wildlife corridors.', 'gma', 'KGMA', 0, -15.0000, 26.0000, -15.0000, 26.0000, '{"type":"Polygon","coordinates":[[[25.0,-15.5],[27.0,-15.5],[27.0,-14.5],[25.0,-14.5],[25.0,-15.5]]]}', 1, 500),
('Zambezi Game Management Area', 'Buffer zone along the Zambezi River corridor.', 'gma', 'ZGMA', 0, -15.5000, 29.0000, -15.5000, 29.0000, '{"type":"Polygon","coordinates":[[[28.5,-16.0],[30.0,-16.0],[30.0,-15.0],[28.5,-15.0],[28.5,-16.0]]]}', 1, 500),
('Liuwa Game Management Area', 'Buffer zone around Liuwa Plain National Park.', 'gma', 'LGMA2', 0, -15.0000, 23.0000, -15.0000, 23.0000, '{"type":"Polygon","coordinates":[[[22.0,-15.5],[24.0,-15.5],[24.0,-14.5],[22.0,-14.5],[22.0,-15.5]]]}', 1, 500),
('Bangweulu Game Management Area', 'Protects the Bangweulu Wetlands ecosystem.', 'gma', 'BGMA', 0, -11.5000, 30.0000, -11.5000, 30.0000, '{"type":"Polygon","coordinates":[[[29.5,-12.0],[30.5,-12.0],[30.5,-11.0],[29.5,-11.0],[29.5,-12.0]]]}', 1, 500),
('West Lunga Game Management Area', 'Buffer zone for the West Lunga National Park area.', 'gma', 'WLGMA', 0, -12.5000, 25.0000, -12.5000, 25.0000, '{"type":"Polygon","coordinates":[[[24.5,-13.0],[25.5,-13.0],[25.5,-12.0],[24.5,-12.0],[24.5,-13.0]]]}', 1, 500);

INSERT INTO lodges (zone_id, name, description, location_lat, location_lng, is_active) VALUES
((SELECT id FROM zones WHERE park_code = 'SLNP' LIMIT 1), 'Mfuwe Lodge', 'Riverside lodge near South Luangwa', -13.0833, 31.5000, 1),
((SELECT id FROM zones WHERE park_code = 'SLNP' LIMIT 1), 'Bilimungwe Camp', 'Bushcamp in the heart of the park', -13.1000, 31.5500, 1),
((SELECT id FROM zones WHERE park_code = 'KNP'  LIMIT 1), 'Kafue River Lodge', 'Lodge on the Kafue River', -14.5000, 26.0000, 1);

INSERT INTO settings (setting_key, setting_value, setting_group) VALUES
('site_name',               'Wildlife Sentinel',                'general'),
('site_tagline',            'Protecting Zambia''s Wildlife',    'general'),
('timezone',                'Africa/Lusaka',                    'general'),
('language',                'en',                               'general'),
('date_format',             'M j, Y H:i',                       'general'),
('items_per_page',          '25',                               'general'),
('sms_enabled',             '1',                                'notifications'),
('email_enabled',           '0',                                'notifications'),
('push_enabled',            '1',                                'notifications'),
('notify_on_incident',      '1',                                'notifications'),
('notify_on_ai_alert',      '1',                                'notifications'),
('notify_on_alarm',         '1',                                'notifications'),
('notify_on_manpower',      '1',                                'notifications'),
('notify_offline_users',    '1',                                'notifications'),
('ai_enabled',              '1',                                'ai'),
('ai_confidence_min',       '70',                               'ai'),
('ai_auto_create_alert',    '1',                                'ai'),
('ai_auto_trigger_alarm',   '0',                                'ai'),
('cctv_retention_days',     '30',                               'ai'),
('cctv_snapshot_dir',       'uploads/cctv/',                    'ai'),
('ai_ingest_key',           '',                                 'ai'),
('session_timeout_min',     '60',                               'security'),
('password_min_length',     '8',                                'security'),
('password_require_upper',  '1',                                'security'),
('password_require_lower',  '1',                                'security'),
('password_require_num',    '1',                                'security'),
('password_require_sym',    '0',                                'security'),
('login_max_attempts',      '5',                                'security'),
('login_lockout_min',       '5',                                'security'),
('maintenance_mode',        '0',                                'maintenance'),
('maintenance_message',     'System under maintenance. Please check back soon.', 'maintenance');

INSERT INTO ai_models (name, version, model_type, framework, input_size, precision_level, avg_latency_ms, accuracy, is_default, notes) VALUES
('yolov8n-detector',   '1.0', 'detector',   'onnx',   '640x640', 'int8', 25,  0.7200, 1, 'Fast general-purpose detector (default)'),
('yolov8s-detector',   '1.0', 'detector',   'onnx',   '640x640', 'fp16', 55,  0.7800, 0, 'Balanced accuracy detector'),
('yolov8m-detector',   '1.0', 'detector',   'onnx',   '640x640', 'fp16', 110, 0.8200, 0, 'Higher accuracy detector (slower)'),
('thermal-detector',   '1.0', 'detector',   'onnx',   '512x512', 'fp16', 60,  0.7400, 0, 'Thermal-specific detector'),
('gunshot-classifier', '1.0', 'classifier', 'tflite', '224x224', 'int8', 12,  0.8900, 0, 'Audio-to-gunshot classifier'),
('fire-classifier',    '1.0', 'classifier', 'tflite', '224x224', 'int8', 14,  0.9100, 0, 'Fire/smoke classifier'),
('behaviour-lstm',     '1.0', 'behavior',   'onnx',   '30x128',  'fp16', 35,  0.8300, 0, 'Behaviour model (loitering, approach, flee)'),
('fusion-scorer',      '1.0', 'fusion',     'custom', 'n/a',     'fp32', 2,   0.9500, 0, 'Weighted ensemble + threat scoring');

INSERT INTO ai_thresholds (zone_id, camera_id, detection_type, min_confidence, min_ensemble_confidence, min_threat_score, min_track_frames, cooldown_seconds) VALUES
(NULL, NULL, 'human',   0.7500, 0.8000, 55.000, 2, 30),
(NULL, NULL, 'vehicle', 0.7000, 0.7500, 45.000, 2, 45),
(NULL, NULL, 'animal',  0.6500, 0.7000, 25.000, 2, 60),
(NULL, NULL, 'fire',    0.7000, 0.7500, 70.000, 1, 15),
(NULL, NULL, 'gunshot', 0.8000, 0.8500, 85.000, 1, 10),
(NULL, NULL, 'unknown', 0.8500, 0.9000, 60.000, 2, 60);

INSERT INTO ai_rules (name, rule_key, description, detection_type, condition_json, threat_level, weight) VALUES
('Human near boundary at night',        'human_boundary_night',    'Human detected near zone boundary during night hours', 'human',   '{"near_boundary":true,"is_night":true}',                          'high',     25.00),
('Human loitering in sensitive area',   'human_loitering',         'Human remaining stationary inside a sensitive area for over 2 min', 'human', '{"behaviour":"loitering","min_duration_seconds":120}',           'high',     22.00),
('Vehicle intrusion into core zone',    'vehicle_intrusion',       'Vehicle detected inside a restricted core zone',        'vehicle', '{"inside_zone":true,"subclass_in":["pickup","truck","suv"]}',   'high',     30.00),
('High-confidence gunshot',             'gunshot_high_conf',       'Gunshot classifier above 0.85 confidence',              'gunshot', '{"min_confidence":0.85}',                                          'critical', 45.00),
('Fire in dry season',                  'fire_dry_season',         'Fire or smoke detected during dry season',              'fire',    '{"min_confidence":0.70,"month_in":[6,7,8,9,10]}',                   'critical', 40.00),
('Animal distress',                     'animal_distress',         'Animal detected with high distress behaviour score',    'animal',  '{"behaviour_score_min":0.75}',                                      'medium',   18.00),
('Rapid approach towards village',      'human_approach_village',  'Human track heading towards nearest village at over 1 m/s', 'human', '{"behaviour":"approaching","min_speed_mps":1.0,"target":"village"}', 'high',   28.00);

CREATE OR REPLACE VIEW incident_summary AS
SELECT i.id, i.category, i.severity, i.status, i.description,
       i.location_lat, i.location_lng, i.reported_at,
       u.full_name AS reporter_name, u.phone AS reporter_phone,
       z.name AS zone_name, i.media_urls
FROM incidents i
LEFT JOIN users u ON i.reporter_id = u.id
LEFT JOIN zones z ON i.zone_id = z.id;
CREATE OR REPLACE VIEW ranger_status AS
SELECT u.id, u.full_name, u.phone, u.zone_id, z.name AS zone_name,
       ra.is_available, ra.current_incident_id,
       i.category AS current_incident_category,
       rlt.current_lat, rlt.current_lng,
       rlt.last_update AS last_location_update
FROM users u
LEFT JOIN ranger_availability ra ON u.id = ra.ranger_id
LEFT JOIN incidents i ON ra.current_incident_id = i.id
LEFT JOIN ranger_live_tracking rlt ON u.id = rlt.ranger_id
LEFT JOIN zones z ON u.zone_id = z.id
WHERE u.role = 'ranger';
CREATE OR REPLACE VIEW unacknowledged_incidents AS
SELECT zone_id, COUNT(*) AS count, string_agg(id::text, ',') AS incident_ids
FROM incidents
WHERE status = 'reported'
GROUP BY zone_id;
CREATE OR REPLACE VIEW park_registration_status AS
SELECT id, name, park_type, park_code, is_registered,
       CASE WHEN is_registered = 1 THEN '✅ Registered' ELSE '🔴 Not Registered' END AS registration_status,
       CASE WHEN is_registered = 1 THEN '#28a745' ELSE '#dc3545' END AS status_color,
       buffer_radius
FROM zones
WHERE park_type IN ('national_park','gma')
ORDER BY park_type, name;
CREATE OR REPLACE VIEW zone_map_data AS
SELECT id, name, park_type, park_code, is_registered,
       boundary_center_lat AS lat, boundary_center_lng AS lng,
       boundary_geojson, buffer_radius
FROM zones
WHERE park_type IN ('national_park','gma');
CREATE OR REPLACE VIEW scout_status AS
SELECT u.id, u.full_name, u.phone, u.email, u.zone_id, z.name AS zone_name,
       u.is_online, u.last_seen,
       slt.current_lat, slt.current_lng,
       slt.last_update AS last_location_update,
       slt.is_offline
FROM users u
LEFT JOIN scout_live_tracking slt ON u.id = slt.scout_id
LEFT JOIN zones z ON u.zone_id = z.id
WHERE u.role = 'scout';
CREATE OR REPLACE VIEW supervisor_dashboard_summary AS
SELECT
    z.id AS zone_id,
    z.name AS zone_name,
    (SELECT COUNT(*) FROM incidents i WHERE i.zone_id = z.id AND i.status NOT IN ('resolved','closed')) AS active_incidents,
    (SELECT COUNT(*) FROM incidents i WHERE i.zone_id = z.id AND i.status = 'reported') AS unacknowledged,
    (SELECT COUNT(*) FROM users u WHERE u.zone_id = z.id AND u.role = 'ranger' AND u.is_on_duty = 1) AS rangers_on_duty,
    (SELECT COUNT(*) FROM users u WHERE u.zone_id = z.id AND u.role = 'ranger' AND u.is_active = 1) AS total_rangers,
    (SELECT COUNT(*) FROM users u WHERE u.zone_id = z.id AND u.role = 'scout' AND u.is_online = 1) AS scouts_online,
    (SELECT COUNT(*) FROM users u WHERE u.zone_id = z.id AND u.role = 'scout' AND u.is_active = 1) AS total_scouts,
    (SELECT COUNT(*) FROM ai_anomalies a WHERE a.zone_id = z.id AND a.detected_at >= (CURRENT_TIMESTAMP - INTERVAL '24 HOUR')) AS ai_anomalies_24h
FROM zones z
WHERE z.is_active = 1;
CREATE OR REPLACE VIEW ai_active_threats AS
SELECT d.id, d.zone_id, z.name AS zone_name, d.camera_id, c.camera_name,
       d.detection_type, d.subclass, d.confidence, d.ensemble_confidence,
       d.threat_level, d.threat_score, d.behaviour, d.behaviour_score,
       d.detected_at, d.snapshot_url, d.location_lat, d.location_lng
FROM ai_detections_v2 d
LEFT JOIN zones z ON d.zone_id = z.id
LEFT JOIN cctv_cameras c ON d.camera_id = c.id
WHERE d.is_threat = 1
  AND d.threat_score >= 50
  AND d.detected_at >= (CURRENT_TIMESTAMP - INTERVAL '1 HOUR')
ORDER BY d.threat_score DESC, d.detected_at DESC;
CREATE OR REPLACE VIEW ai_recent_detections AS
SELECT d.id, d.zone_id, z.name AS zone_name,
       d.camera_id, c.camera_name,
       d.detection_type, d.subclass, d.confidence, d.ensemble_confidence,
       d.is_threat, d.threat_level, d.threat_score,
       d.track_id, d.behaviour, d.is_night, d.inside_zone,
       m.name AS model_name, m.version AS model_version,
       d.detected_at, d.snapshot_url
FROM ai_detections_v2 d
LEFT JOIN zones z ON d.zone_id = z.id
LEFT JOIN cctv_cameras c ON d.camera_id = c.id
LEFT JOIN ai_models m ON d.model_id = m.id
ORDER BY d.detected_at DESC;

CREATE FUNCTION ws_assignment_insert() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.status = 'accepted' THEN UPDATE ranger_availability SET is_available=0, current_incident_id=NEW.incident_id WHERE ranger_id=NEW.ranger_id; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER update_ranger_availability_on_assignment AFTER INSERT ON incident_assignments FOR EACH ROW EXECUTE FUNCTION ws_assignment_insert();
CREATE FUNCTION ws_incident_resolved() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.status='resolved' AND OLD.status<>'resolved' THEN UPDATE ranger_availability SET is_available=1,current_incident_id=NULL WHERE current_incident_id=NEW.id; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER update_ranger_availability_on_resolution AFTER UPDATE ON incidents FOR EACH ROW EXECUTE FUNCTION ws_incident_resolved();
CREATE FUNCTION ws_incident_point() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='INSERT' THEN
   IF NEW.location_geojson IS NULL
      OR (NEW.location_geojson[0] = 0 AND NEW.location_geojson[1] = 0)
   THEN
      NEW.location_geojson := point(NEW.location_lng, NEW.location_lat);
   END IF;
 ELSIF NEW.location_lat IS DISTINCT FROM OLD.location_lat OR NEW.location_lng IS DISTINCT FROM OLD.location_lng THEN
   NEW.location_geojson := point(NEW.location_lng, NEW.location_lat);
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER set_incident_location_geojson BEFORE INSERT OR UPDATE ON incidents FOR EACH ROW EXECUTE FUNCTION ws_incident_point();
CREATE FUNCTION ws_zone_insert() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 INSERT INTO zone_notification_settings (zone_id,sms_enabled,alarm_enabled,ai_detection_enabled) VALUES (NEW.id,1,1,1) ON CONFLICT DO NOTHING;
 INSERT INTO zone_system_settings (zone_id) VALUES (NEW.id) ON CONFLICT DO NOTHING;
 INSERT INTO zone_ai_settings (zone_id) VALUES (NEW.id) ON CONFLICT DO NOTHING;
 RETURN NEW;
END $$;
CREATE TRIGGER create_zone_notification_settings AFTER INSERT ON zones FOR EACH ROW EXECUTE FUNCTION ws_zone_insert();
CREATE FUNCTION ws_scout_insert() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 UPDATE users SET is_online=1,last_seen=NOW() WHERE id=NEW.scout_id;
 RETURN NEW;
END $$;
CREATE TRIGGER mark_scout_online AFTER INSERT ON scout_live_tracking FOR EACH ROW EXECUTE FUNCTION ws_scout_insert();

-- Reporting functions return result sets.
CREATE FUNCTION GetNearbyIncidents(p_lat DECIMAL(10,8),
    p_lng DECIMAL(11,8),
    p_radius integer,
    p_limit integer) RETURNS TABLE (id integer, reporter_id integer, reporter_type text, zone_id integer, category text, severity text, description text, location_lat numeric(10,8), location_lng numeric(11,8), location_geojson point, media_urls jsonb, status text, reported_at timestamp without time zone, acknowledged_by integer, acknowledged_at timestamp without time zone, resolved_at timestamp without time zone, is_simulated smallint, distance double precision) LANGUAGE sql STABLE AS $$
SELECT * FROM (SELECT *,
           (6371 * ACOS(COS(RADIANS(p_lat)) * COS(RADIANS(location_lat)) *
            COS(RADIANS(location_lng) - RADIANS(p_lng)) +
            SIN(RADIANS(p_lat)) * SIN(RADIANS(location_lat)))) AS distance
    FROM incidents
    WHERE status NOT IN ('resolved','closed')
    ) AS nearby WHERE distance < p_radius 
    ORDER BY distance ASC, CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 ELSE 0 END
    LIMIT p_limit;
$$;
CREATE FUNCTION GetZoneStatistics(p_zone_id integer) RETURNS TABLE (active_incidents bigint, unacknowledged bigint, today_reports bigint, available_rangers bigint, total_rangers bigint, incidents_with_photos bigint) LANGUAGE sql STABLE AS $$
SELECT
        (SELECT COUNT(*) FROM incidents WHERE zone_id = p_zone_id AND status NOT IN ('resolved','closed')) AS active_incidents,
        (SELECT COUNT(*) FROM incidents WHERE zone_id = p_zone_id AND status = 'reported') AS unacknowledged,
        (SELECT COUNT(*) FROM incidents WHERE zone_id = p_zone_id AND DATE(reported_at) = CURRENT_DATE) AS today_reports,
        (SELECT COUNT(*) FROM ranger_availability ra JOIN users u ON ra.ranger_id = u.id WHERE u.zone_id = p_zone_id AND ra.is_available = 1) AS available_rangers,
        (SELECT COUNT(*) FROM users WHERE zone_id = p_zone_id AND role = 'ranger' AND is_active = 1) AS total_rangers,
        (SELECT COUNT(*) FROM incidents WHERE zone_id = p_zone_id AND media_urls IS NOT NULL) AS incidents_with_photos;
$$;
CREATE FUNCTION GetSystemStatistics() RETURNS TABLE (total_users bigint, total_rangers bigint, total_incidents bigint, active_incidents bigint, unacknowledged bigint, total_zones bigint, total_messages bigint, unread_notifications bigint, incidents_with_photos bigint, registered_parks bigint, available_parks bigint) LANGUAGE sql STABLE AS $$
SELECT
        (SELECT COUNT(*) FROM users) AS total_users,
        (SELECT COUNT(*) FROM users WHERE role = 'ranger') AS total_rangers,
        (SELECT COUNT(*) FROM incidents) AS total_incidents,
        (SELECT COUNT(*) FROM incidents WHERE status NOT IN ('resolved','closed')) AS active_incidents,
        (SELECT COUNT(*) FROM incidents WHERE status = 'reported') AS unacknowledged,
        (SELECT COUNT(*) FROM zones WHERE is_active = 1) AS total_zones,
        (SELECT COUNT(*) FROM messages) AS total_messages,
        (SELECT COUNT(*) FROM notifications WHERE is_read = 0) AS unread_notifications,
        (SELECT COUNT(*) FROM incidents WHERE media_urls IS NOT NULL) AS incidents_with_photos,
        (SELECT COUNT(*) FROM zones WHERE park_type IN ('national_park','gma') AND is_registered = 1) AS registered_parks,
        (SELECT COUNT(*) FROM zones WHERE park_type IN ('national_park','gma') AND is_registered = 0) AS available_parks;
$$;
CREATE FUNCTION GetZoneRangersLive(p_zone_id integer) RETURNS TABLE (id integer, full_name character varying(255), phone character varying(20), badge_number character varying(50), is_on_duty smallint, current_lat numeric(10,8), current_lng numeric(11,8), heading numeric(5,2), speed numeric(6,2), location_updated timestamp without time zone, is_offline smallint) LANGUAGE sql STABLE AS $$
SELECT u.id, u.full_name, u.phone, u.badge_number, u.is_on_duty,
           rlt.current_lat, rlt.current_lng, rlt.heading, rlt.speed,
           rlt.last_update AS location_updated, rlt.is_offline
    FROM users u
    LEFT JOIN ranger_live_tracking rlt ON u.id = rlt.ranger_id
    WHERE u.zone_id = p_zone_id AND u.role = 'ranger' AND u.is_active = 1
    ORDER BY u.is_on_duty DESC, u.full_name ASC;
$$;
CREATE FUNCTION GetZoneScoutsLive(p_zone_id integer) RETURNS TABLE (id integer, full_name character varying(255), phone character varying(20), email character varying(255), is_online smallint, last_seen timestamp without time zone, current_lat numeric(10,8), current_lng numeric(11,8), location_updated timestamp without time zone, is_offline smallint) LANGUAGE sql STABLE AS $$
SELECT u.id, u.full_name, u.phone, u.email, u.is_online, u.last_seen,
           slt.current_lat, slt.current_lng,
           slt.last_update AS location_updated, slt.is_offline
    FROM users u
    LEFT JOIN scout_live_tracking slt ON u.id = slt.scout_id
    WHERE u.zone_id = p_zone_id AND u.role = 'scout' AND u.is_active = 1
    ORDER BY u.is_online DESC, u.last_seen DESC;
$$;
CREATE FUNCTION GetZoneAIAnomalies(p_zone_id integer, p_limit integer) RETURNS TABLE (id integer, zone_id integer, type text, severity text, description text, confidence numeric(4,3), location_lat numeric(10,8), location_lng numeric(11,8), radius_meters integer, ranger_id integer, scout_id integer, is_acknowledged smallint, acknowledged_by integer, acknowledged_at timestamp without time zone, detected_at timestamp without time zone, subject_name character varying(255), subject_role text) LANGUAGE sql STABLE AS $$
SELECT a.*, u.full_name AS subject_name, u.role AS subject_role
    FROM ai_anomalies a
    LEFT JOIN users u ON (a.ranger_id = u.id OR a.scout_id = u.id)
    WHERE a.zone_id = p_zone_id
      AND a.detected_at >= (NOW() - (24) * INTERVAL '1 hour')
    ORDER BY a.detected_at DESC
    LIMIT p_limit;
$$;

CREATE TABLE ws_schema_versions (version text PRIMARY KEY, applied_at timestamp DEFAULT CURRENT_TIMESTAMP);
INSERT INTO ws_schema_versions (version) VALUES ('wildlife-postgres-v2');
COMMIT;
